### PR TITLE
Fix formatting according to clang-format-6.0

### PR DESCRIPTION
**Pull request by RShaw026**
## Description and Context

In PR #70, proper formatting according to clang-format-6.0 was not followed. This PR formats all the files properly.

## Related Issues and Pull Requests

* Closes
* Blocks
* Is blocked by
* Follows #69 
* Precedes
* Related to #20 
* Part of
* Composed of

## How Has This Been Tested?

build and `ctest`.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers and are longer than one line where appropriate.
- [x] I have added/updated documentation where necessary.

## Interested Parties / Possible Reviewers

@mayrmt

### CODE REVIEW

**Comment by RShaw026** [comment]
@mayrmt @NoraHagmeyer Do you have any ideas on how to enforce the clang format so that we can solve #20 and clean up the repository?

**Comment by NoraHagmeyer** [comment]
> @mayrmt @NoraHagmeyer Do you have any ideas on how to enforce the clang format so that we can solve #20 and clean up the repository?

also looping in @isteinbrecher

**Comment by RShaw026** [comment]
I tried setting up `clang-format-check.yml` in the branch `20-enforce-clang-format` using the method in the following link. https://github.com/jidicula/clang-format-action

I got the following error in the workflow.
[Error: .github#L1](https://github.com/imcs-compsim/MIRCO/commit/a6ee163d25a8ec6eec4d89d48cc05d3437690fe3#annotation_7094538414)
jidicula/clang-format-action@v4.9.0 is not allowed to be used in imcs-compsim/MIRCO. Actions in this workflow must be: within a repository owned by imcs-compsim or created by GitHub.

**Review by mayrmt — APPROVED** [review]
Changes look good, though if we care about code formatting, then we should enforce it.

**Pull request merged**
