### PR TITLE
Add Cmake variables for googletest and Trilinos

### PR DESCRIPTION
**Pull request by RShaw026**
## Description and Context

This will enable MIRCO to be used as a library in projects where the dependencies of MIRCO, i.e. googletest and Trilinos, are already present so that the problems of duplicate dependencies can be avoided.

## Related Issues and Pull Requests

* Closes
* Blocks
* Is blocked by
* Follows
* Precedes
* Related to
* Part of
* Composed of

## How Has This Been Tested?

code builds, and tests are passing. Tested with BACI, using FetchContent and commit hash.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers and are longer than one line where appropriate.
- [ ] I have added/updated documentation where necessary.

## Interested Parties / Possible Reviewers

@mayrmt

### CODE REVIEW

**Comment by mayrmt** [comment]
In principle, this looks good. Do we have specific requirements on the version of Trilinos and googletest? If yes, then we should make sure, that they are met. 

For Trilinos, I believe that we currently do not rely on a specific version. Since we just use `Teuchos`, which is well matured and stable, a version check does not bring any benefits. That might change in the future, if we use other actively developed packages, but for now there's seems to be no need for a version check.

@RShaw026 Do you have insight into googletest in that regard?

**Comment by RShaw026** [comment]
@mayrmt I am not sure if I understand your question correctly.  Once in a while, I update the googletest submodule in MIRCO and change the tests if required. Since we don't need to test MIRCO gtest when MIRCO is integrated into BACI, should I also not build the `tests` by moving that part of code inside the `GTEST_IN_MIRCO` flag? That way even if the googletest in BACI is incompatible with the tests written in MIRCO, it won't fail the BACI build in any way.

**Comment by mayrmt** [comment]
@RShaw026 I haven't thought about that, but you're right: moving the MIRCO tests inside `GTEST_IN_MIRCO` would be the consequence. How much effort is this? What would be the impact on further development and adding tests in MIRCO?

**Review by mayrmt — APPROVED** [review]
@RShaw026 Looks good! How do we guarantee, that we enable GTEST by default? It is really crucial, that MIRCO as a standalone-solver always runs its tests (and that we do not disable them accidentally).

**Comment by RShaw026** [comment]
@mayrmt The flag in the `do-configure` never needs to be changed. It will always be turned on. BACI can still fetch MIRCO with an OFF flag. 

Strangely, if it is turned off in the `do-configure` file, the pipeline buildtest still passes (I checked it now). Should we need the fix that? 
https://github.com/imcs-compsim/MIRCO/actions/runs/4204799074
Is there a way to make the tests fail if the tests are not found?

**Pull request merged**
