### PR TITLE
Modernize CMake to use targets

### PR DESCRIPTION
**Pull request by sebproell**
## Description and Context

As discussed with @mayrmt @RShaw026  this PR suggests a few first steps towards a modern CMake which uses targets and properties on targets consistently. 

## How Has This Been Tested?

Built locally and executed unit tests.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers and are longer than one line where appropriate.
- [x] I have added/updated documentation where necessary.

## Interested Parties / Possible Reviewers

@mayrmt @RShaw026

### CODE REVIEW

**Review by mayrmt — APPROVED** [review]

**Comment by RShaw026** [comment]
I checked out this branch and checked if it worked with the BACI integration, and I have a few comments.

1. We have to do something like the following for the header files in BACI to work when using `fetch_content`. I am not sure if this is the best way to do it.
```
target_include_directories(mirco_lib INTERFACE
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/src/>
    )
```

2. When using `MIRCO_DEVELOP`, i.e. precompiled MIRCO: Even though the precompiled `mirco_library` has OpenMP, I am getting the same linker errors, i.e undefined reference to the MIRCO functions, and errors because of OpenMP.

I tried making it as a SHARED library somehow (not in a good way) and everything works.

**Comment by RShaw026** [comment]
> Indentation seems to be inconsistent now. Sometimes 2 spaces, sometimes more than 2.
> 
> @RShaw026 Do we have a CMake formatting guide line in place? Maybe even automated CMake formatting?

We still don't have a standard to format CMake files, but we can take inspiration from how it is done in BACI and do something like `code_format_everything` in MIRCO.

**Comment by sebproell** [comment]
> I checked out this branch and checked if it worked with the BACI integration, and I have a few comments.
> 
@RShaw026 I would suggest to merge this first cleanup step and tackle the (previously existing) problems with BACI integration afterwards. You are right that you need a `target_include_directories` like the one you added above. For the install, you probably missed to install some transitive dependencies.

**Comment by RShaw026** [comment]
Sure, we can merge this PR.

**Comment by RShaw026** [comment]
Thank you, @sebproell, for your support in modernizing CMake in MIRCO. Merging this PR.

**Pull request merged**
