### PR TITLE
Add version numbering

### LINKED ISSUE #62: Add version number
## Description

To clearly identify the version of MIRCO, e.g. to be used for a publication or to interface with another code, we should add a version number. I propose to follow the concept of semantic versioning (www.semver.org). 

## Possible Solution and Definition of Done

- [ ] Decide on version number scheme
- [ ] Implement/set version number in `CMakeLists.txt`
- [ ] Document version numbering
- [ ] Release a first version of MIRCO

## Related Issues and Merge Requests

* Follows #54

## Interested Parties

@RShaw026 @NoraHagmeyer

### PR DESCRIPTION
**Pull request by mayrmt**
## Description and Context

Add support for semantic version numbering as proposed at www.semver.org.

The version number will help to clearly identify a given version of the code, e.g. for interfering with other codes or for publications.

## Related Issues and Pull Requests

* Closes #62 

## How Has This Been Tested?

- When configuring locally, the version number and its individual components are written to `CMakeCache.txt`.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers and are longer than one line where appropriate.
- [ ] I have added/updated documentation where necessary.

## Interested Parties / Possible Reviewers

@RShaw026 @NoraHagmeyer

### CODE REVIEW

**Comment by NoraHagmeyer** [comment]
For some reason the workflow does not get picked up by the runner.. this might have something to do with the setting changes

**Comment by mayrmt** [comment]
This PR now just adds a first version number, which we then can use to create our first release. I can't think of any other required changes right now. So from my side, this is ready to be merged. Any other ideas?

**Comment by NoraHagmeyer** [comment]
> This PR now just adds a first version number, which we then can use to create our first release. I can't think of any other required changes right now. So from my side, this is ready to be merged. Any other ideas?

I can't think of anything either. Seems fine to be.. I'd let @RShaw026 review it when he gets back though

**Comment by RShaw026** [comment]
Seems fine to me as well. So In case we add some small features or fix some issues/bugs, do we also have to update the version number with the commits?

**Review by RShaw026 — APPROVED** [review]

**Comment by mayrmt** [comment]
@RShaw026 There are some guidelines, when to change the version number. I think, we should observe the frequency of changes and discuss this as we go. I don't think that one needs to change the version number with every PR.

**Pull request merged**
