### PR TITLE
Convert some libraries from static to dynamic

### PR DESCRIPTION
**Pull request by RShaw026**
## Description and Context

When used as an external library in BACI, some linker issues occurred because of the use of a static library. Therefore, `mirco_library` target is converted to dynamic library and OpenMP dependency in added to it. The ideal case would be to make `mirco` as a dynamic library, but I was facing some issues regarding that. So I will open an issue regarding it. Merging this PR is required to move ahead with our BACI/MIRCO integration.
Also, `-Werror` compiler flag is added to treat warnings as errors in the pipeline. 

## Related Issues and Pull Requests

* Closes
* Blocks
* Is blocked by
* Follows
* Precedes
* Related to
* Part of
* Composed of

## How Has This Been Tested?

`ctest` is working. `mirco` executable is working. `mirco_library` is used in BACI in my local, and it is working.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers and are longer than one line where appropriate.
- [ ] I have added/updated documentation where necessary.

## Interested Parties / Possible Reviewers

@mayrmt

### CODE REVIEW

**Review by mayrmt — APPROVED** [review]
Looks good to me. 

@maxfirmbach  Can you also have a look, please?

**Comment by RShaw026** [comment]
To avoid printing the Trilinos configuration messages while building BACI, I have moved them inside the `TRILINOS_IN_MIRCO` flag. These things will help us to integrate MIRCO into BACI; however, the CMakeLists in MIRCO need to be redesigned.

**Comment by RShaw026** [comment]
After the meeting with Sebastian Pröll, I think we can go ahead with the merge request as the current target `mirco_library` is enough for BACI. So that BACI is merge-ready as it does not have to care about the internal changes in MIRCO CMake. I am working on his comments to modernize MIRCO CMake.

**Comment by mayrmt** [comment]
Let's with this PR until PR #78 has been merged.

**Pull request closed without merging**
